#!/bin/bash

set -euo pipefail

:prompt() {
    local _var="$1"
    local _text="$2"

    echo -n "$_text"
    read _value

    eval $_var=\$_value
}

:exec() {
    logger "shadowc-change-password: exec $*"
    "$@"
}

:prompt pool "Pool: "
:prompt user "User: "

if [[ "${pool:-}" ]]; then
    :exec shadowc -P --pool "$pool" --user "$user"
else
    :exec shadowc -P --user "$user"
fi
